# Generated by Django 5.2 on 2026-05-11 01:42

import django.db.models.deletion
import fantasy.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('golf', '0003_player_wiki_bio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('roster_size', models.IntegerField(default=6)),
                ('invite_code', models.CharField(default=fantasy.models._invite_code, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commissioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissioner_leagues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeagueMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='fantasy.league')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('league', 'user')},
            },
        ),
        migrations.AddField(
            model_name='league',
            name='members',
            field=models.ManyToManyField(related_name='leagues', through='fantasy.LeagueMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WeeklyDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('locked', 'Locked'), ('scored', 'Scored')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='fantasy.league')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='golf.tournament')),
            ],
            options={
                'unique_together': {('league', 'tournament')},
            },
        ),
        migrations.CreateModel(
            name='DraftPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picked_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_picks', to='golf.player')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='fantasy.leaguemember')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='fantasy.weeklydraft')),
            ],
            options={
                'unique_together': {('draft', 'member', 'player')},
            },
        ),
    ]
