# Generated by Django 5.2 on 2026-05-11 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0001_initial'),
        ('golf', '0003_player_wiki_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draftpick',
            options={'ordering': ['pick_number']},
        ),
        migrations.AlterUniqueTogether(
            name='draftpick',
            unique_together={('draft', 'player')},
        ),
        migrations.AddField(
            model_name='draftpick',
            name='pick_number',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DraftOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='fantasy.weeklydraft')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_order', to='fantasy.leaguemember')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('draft', 'position')},
            },
        ),
    ]
