# Generated by Django 5.2 on 2026-05-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0002_alter_draftpick_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklydraft',
            name='draft_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
