# Generated by Django 5.2 on 2026-05-12 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0003_add_draft_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklydraft',
            name='current_pick_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklydraft',
            name='pick_time_limit',
            field=models.IntegerField(default=120),
        ),
    ]
