# Generated by Django 5.2 on 2026-05-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0004_add_pick_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklydraft',
            name='seconds_at_pause',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklydraft',
            name='timer_paused',
            field=models.BooleanField(default=False),
        ),
    ]
