# Generated by Django 5.2 on 2026-05-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0005_add_timer_pause'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguemember',
            name='team_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
