# Generated by Django 5.2 on 2026-05-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_player_bio_note_player_bio_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='wiki_bio',
            field=models.TextField(blank=True),
        ),
    ]
