# Generated by Django 5.2 on 2026-05-15 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0003_player_wiki_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='wiki_bio',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='CourseHole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('par', models.IntegerField()),
                ('yardage', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holes', to='golf.course')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('course', 'number')},
            },
        ),
    ]
