# Generated by Django 5.2 on 2026-05-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0004_course_wiki_bio_coursehole'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerscore',
            name='tee_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
